# Exported from Render on 2024-07-08T18:19:13Z
services:
- type: web
  name: FOOD_DELIVERY_APP
  runtime: node
  repo: https://github.com/rinsi-Gupta/Food-Delivery-App
  plan: free
  envVars:
  - key: PORT
    sync: false
  - key: DOMAIN
    sync: false
  - key: STRIPE_SECRET_KEY
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: MONGODB_URL
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
  rootDir: backend
version: "1"
